alias c='clear'
alias push='git push'
alias pull='git pull'
alias repo='cd /Volumes/ZOHO/repo/zoholivesupport'
alias v2='run-dev webpack'
alias v3='run-dev v3'
alias branch='git branch'
alias mybranch='switchbranch ZOHOLIVESUPPORT_NARENDEREN_BRANCH'
alias newui='switchbranch ZOHOLIVESUPPORT_NEWUI_BRANCH'
alias mergemybranch='mergebranch ZOHOLIVESUPPORT_NARENDEREN_BRANCH'
alias mergenewui='mergebranch ZOHOLIVESUPPORT_NEWUI_BRANCH'
alias mergemaster='mergebranch master'
alias log='git log --graph --pretty=oneline'